spring:
  datasource:
    url: jdbc:mysql://keycloak-db.cfnumbgq78gc.ap-northeast-2.rds.amazonaws.com:3306/reddy?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
